"""file path

Revision ID: 0a090995f64f
Revises: 324cab2b2f96
Create Date: 2025-03-15 21:56:34.911678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a090995f64f'
down_revision: Union[str, None] = '324cab2b2f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingextracts', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('meetingextracts', 'transcript_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meetingextracts', 'summary_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetingextracts', 'summary_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meetingextracts', 'transcript_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('meetingextracts', 'file_path')
    # ### end Alembic commands ###
