"""removed constrainsts

Revision ID: 2aa3eb641e2e
Revises: dbea36d51b0b
Create Date: 2024-10-06 09:24:03.887498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2aa3eb641e2e'
down_revision: Union[str, None] = 'dbea36d51b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
