"""meeting extracts

Revision ID: 324cab2b2f96
Revises: f48560ab22a3
Create Date: 2025-01-30 20:25:46.936335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '324cab2b2f96'
down_revision: Union[str, None] = 'f48560ab22a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetingextracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.rid'], ),
    sa.PrimaryKeyConstraint('id', 'room_id')
    )
    op.drop_column('room', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('meetingextracts')
    # ### end Alembic commands ###
